In [1]:
import torch
torch.__version__


'2.3.0'

In [3]:
x = torch.empty(4,2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
x = torch.rand(4,2)
x

tensor([[0.7841, 0.2717],
        [0.3353, 0.8528],
        [0.6124, 0.8460],
        [0.0621, 0.8897]])

In [5]:
x = torch.zeros(4,2, dtype = torch.long)
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [6]:
x = torch.tensor([3,2.3])
x

tensor([3.0000, 2.3000])

In [7]:
x = x.new_ones(2,4, dtype = torch.double)
x
# new_ones, new_zeros, new_full (shape 다음에 값을 넣으면 그 값으로 채워짐), new_empty

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [8]:
# 기존의 텐서 모양이랑 같은걸로 만들어라
x = torch.randn_like(x, dtype = torch.float)
x

tensor([[1.2177, 1.4166, 0.4928, 0.4677],
        [0.8268, 0.0197, 2.6270, 1.4591]])

In [9]:
print(x.size()
      )

torch.Size([2, 4])


In [10]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [12]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [13]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [14]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


CUDA Tensors

.to 메소드를 사용하여 텐서를 어떠한 장치로 옮길수 있음


In [16]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.4220])
0.4219599962234497
torch.float32


In [18]:
print(torch.backends.mps.is_available()) # MPS 장치가 사용 가능한지 확인합니다. True여야 합니다.



True


In [27]:
device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')
print(device)
y = torch.ones_like(x,device = device)
print(y)
x = x.to(device)
print(x)
z = x+y
print(z)
print(z.to('cpu', torch.float))

mps
tensor([1.], device='mps:0')
tensor([0.4220], device='mps:0')
tensor([1.4220], device='mps:0')
tensor([1.4220])


다차원 텐서 표현

In [28]:
# 0d tensor
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [29]:
# 1D tensor
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [30]:
# 2D tensor
t2 = torch.tensor([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [31]:
# 3D tensor
t3 = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                   [[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                   [[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


텐서의 연산

In [36]:
import math

a = torch.rand(1,2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[-0.3363, -0.8073]])
tensor([[0.3363, 0.8073]])
tensor([[-0., -0.]])
tensor([[-1., -1.]])
tensor([[-0.3363, -0.5000]])


In [37]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,2])))

tensor([[-0.3363, -0.8073]])
tensor(-0.8073)
tensor(-0.3363)
tensor(-0.5718)
tensor(0.3330)
tensor(0.2715)
tensor([1, 2, 3])


In [41]:
# max 와 min은 dim 인자를 줄 경우 argmax와 argmin도 함께 리턴
# argmax: 최대값을 가진 인덱스
# argmin: 최소값을 가진 인덱스
# dim = 0 은 column
# dim = 1 은 row
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.2988, 0.8890],
        [0.8963, 0.3705]])
torch.return_types.max(
values=tensor([0.8963, 0.8890]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([0.8890, 0.8963]),
indices=tensor([1, 0]))


In [42]:
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.2988, 0.8890],
        [0.8963, 0.3705]])
torch.return_types.min(
values=tensor([0.2988, 0.3705]),
indices=tensor([0, 1]))
torch.return_types.min(
values=tensor([0.2988, 0.3705]),
indices=tensor([0, 1]))


In [43]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.8380, 0.7601],
        [0.2766, 0.6400]])
tensor([[0.7083, 0.8726],
        [0.9300, 0.1533]])


torch.add: 덧셈


In [44]:
print(x+y)
print(torch.add(x,y))

tensor([[1.5463, 1.6327],
        [1.2066, 0.7932]])
tensor([[1.5463, 1.6327],
        [1.2066, 0.7932]])


In [46]:
result = torch.empty(2,4)
print(result)
torch.add(x,y, out = result)
print(result)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1.5463, 1.6327],
        [1.2066, 0.7932]])


/var/folders/mk/3rm9f8jj0_54616_xx1g__n00000gn/T/ipykernel_15284/450674821.py:3: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/Resize.cpp:35.)
  torch.add(x,y, out = result)


```python
in-place 방식
```
* in-place 방식으로 텐서의 값을 변경하는 연산 뒤에서는 _"가 붙음
* ``` x.copy_(y), x.t_(x) ```


In [47]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.8380, 0.7601],
        [0.2766, 0.6400]])
tensor([[0.7083, 0.8726],
        [0.9300, 0.1533]])
tensor([[1.5463, 1.6327],
        [1.2066, 0.7932]])


In [48]:
print(x)
print(y)
print(x - y)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[0.8380, 0.7601],
        [0.2766, 0.6400]])
tensor([[1.5463, 1.6327],
        [1.2066, 0.7932]])
tensor([[-0.7083, -0.8726],
        [-0.9300, -0.1533]])
tensor([[-0.7083, -0.8726],
        [-0.9300, -0.1533]])
tensor([[-0.7083, -0.8726],
        [-0.9300, -0.1533]])


In [49]:
print(x)
print(y)
print(x * y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[0.8380, 0.7601],
        [0.2766, 0.6400]])
tensor([[1.5463, 1.6327],
        [1.2066, 0.7932]])
tensor([[1.2958, 1.2409],
        [0.3338, 0.5077]])
tensor([[1.2958, 1.2409],
        [0.3338, 0.5077]])
tensor([[1.2958, 1.2409],
        [0.3338, 0.5077]])


In [50]:
print(x)
print(y)
print(x / y)
print(torch.div(x,y))
print(x.div(y))

tensor([[0.8380, 0.7601],
        [0.2766, 0.6400]])
tensor([[1.5463, 1.6327],
        [1.2066, 0.7932]])
tensor([[0.5419, 0.4655],
        [0.2293, 0.8068]])
tensor([[0.5419, 0.4655],
        [0.2293, 0.8068]])
tensor([[0.5419, 0.4655],
        [0.2293, 0.8068]])


In [51]:
# torch.mm: 내적 (dot product)
print(x)
print(y)

print(torch.matmul(x,y))
z = torch.mm(x,y)
print(z)
print(torch.svd(z))

tensor([[0.8380, 0.7601],
        [0.2766, 0.6400]])
tensor([[1.5463, 1.6327],
        [1.2066, 0.7932]])
tensor([[2.2129, 1.9711],
        [1.2000, 0.9593]])
tensor([[2.2129, 1.9711],
        [1.2000, 0.9593]])
torch.return_types.svd(
U=tensor([[-0.8879, -0.4599],
        [-0.4599,  0.8879]]),
S=tensor([3.3372, 0.0726]),
V=tensor([[-0.7542,  0.6567],
        [-0.6567, -0.7542]]))


### 텐서의 조작 (Manipulations)


In [53]:
x = torch.Tensor([[1,2],
                 [3,4]])
print(x)
print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])

print(x[:,0])
print(x[:,1])


tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])


``` view```: 텐서의 크기나 모양을 변경
* 기본적으로 변경 전과 후에 텐서 안의 원소 개수가 유지되어야함
* -1로 설정되면 계산을 통해 해당 크기값을 유추


In [58]:
x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = x.view(10,-1)
print(z)

tensor([[-0.3698, -1.9336, -0.1553, -0.2075,  0.5781],
        [-0.3389, -0.6679,  0.1736,  0.0565,  0.2302],
        [ 0.4520, -1.8762,  0.1671,  0.4431, -0.9889],
        [-0.7728,  0.0598,  0.3785,  1.4025,  1.0198]])
tensor([-0.3698, -1.9336, -0.1553, -0.2075,  0.5781, -0.3389, -0.6679,  0.1736,
         0.0565,  0.2302,  0.4520, -1.8762,  0.1671,  0.4431, -0.9889, -0.7728,
         0.0598,  0.3785,  1.4025,  1.0198])
tensor([[-0.3698, -1.9336],
        [-0.1553, -0.2075],
        [ 0.5781, -0.3389],
        [-0.6679,  0.1736],
        [ 0.0565,  0.2302],
        [ 0.4520, -1.8762],
        [ 0.1671,  0.4431],
        [-0.9889, -0.7728],
        [ 0.0598,  0.3785],
        [ 1.4025,  1.0198]])


In [62]:
# item: 텐서의 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)
# 아이템이 하나 일때만 가능


tensor([-0.0231])
-0.02310161292552948
torch.float32


In [63]:
# squeeze: 차원을 축소 (제거)
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.2865, 0.1330, 0.6921],
         [0.6174, 0.0316, 0.8175],
         [0.4251, 0.0159, 0.4145]]])
torch.Size([1, 3, 3])


In [64]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.2865, 0.1330, 0.6921],
        [0.6174, 0.0316, 0.8175],
        [0.4251, 0.0159, 0.4145]])
torch.Size([3, 3])


In [66]:
# unsqueeze: 차원을 증가 (생성)
t = torch.rand(3,3)
print(t)
print(t.shape)
tensor = t.unsqueeze(dim = 0)
print(tensor)
print(tensor.shape)

tensor([[0.0918, 0.4735, 0.9566],
        [0.0020, 0.6181, 0.6006],
        [0.9212, 0.0410, 0.6478]])
torch.Size([3, 3])
tensor([[[0.0918, 0.4735, 0.9566],
         [0.0020, 0.6181, 0.6006],
         [0.9212, 0.0410, 0.6478]]])
torch.Size([1, 3, 3])


In [67]:
tensor = t.unsqueeze(dim = 2)
print(tensor)
print(tensor.shape)

tensor([[[0.0918],
         [0.4735],
         [0.9566]],

        [[0.0020],
         [0.6181],
         [0.6006]],

        [[0.9212],
         [0.0410],
         [0.6478]]])
torch.Size([3, 3, 1])


In [68]:
tensor = t.unsqueeze(dim = 1)
print(tensor)
print(tensor.shape)

tensor([[[0.0918, 0.4735, 0.9566]],

        [[0.0020, 0.6181, 0.6006]],

        [[0.9212, 0.0410, 0.6478]]])
torch.Size([3, 1, 3])


In [69]:
# stack: 텐서간 결합
x = torch.FloatTensor([1,4])
print(x)
y = torch.FloatTensor([2,5])
print(y)
z = torch.FloatTensor([3,6])
print(z)

print(torch.stack([x,y,z]))

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [70]:
# cat: 텐서를 결합
# 넘파이의 stack과 유사하지만, 쌓을 dim 존재해야함
# 해달 차원을 늘려준 후 결합

a = torch.randn(1,3,3)
print(a)
b = torch.randn(1,3,3)
print(b)
c = torch.cat((a,b), dim=0)
print(c)
print(c.size())

tensor([[[ 0.0995,  0.0329,  1.1276],
         [-0.7671,  1.8259,  2.2172],
         [-0.0417,  0.9871,  0.8185]]])
tensor([[[-0.1623, -0.0196, -0.4343],
         [ 0.2518, -0.0243,  0.3980],
         [-1.4870,  0.0253, -0.5938]]])
tensor([[[ 0.0995,  0.0329,  1.1276],
         [-0.7671,  1.8259,  2.2172],
         [-0.0417,  0.9871,  0.8185]],

        [[-0.1623, -0.0196, -0.4343],
         [ 0.2518, -0.0243,  0.3980],
         [-1.4870,  0.0253, -0.5938]]])
torch.Size([2, 3, 3])


In [71]:
c = torch.cat((a,b), dim=1)
print(c)
print(c.size())

tensor([[[ 0.0995,  0.0329,  1.1276],
         [-0.7671,  1.8259,  2.2172],
         [-0.0417,  0.9871,  0.8185],
         [-0.1623, -0.0196, -0.4343],
         [ 0.2518, -0.0243,  0.3980],
         [-1.4870,  0.0253, -0.5938]]])
torch.Size([1, 6, 3])


In [72]:
c = torch.cat((a,b), dim=2)
print(c)
print(c.size())

tensor([[[ 0.0995,  0.0329,  1.1276, -0.1623, -0.0196, -0.4343],
         [-0.7671,  1.8259,  2.2172,  0.2518, -0.0243,  0.3980],
         [-0.0417,  0.9871,  0.8185, -1.4870,  0.0253, -0.5938]]])
torch.Size([1, 3, 6])


In [74]:
# chunk: 텐서를 여러개로 나눌때 사용
tensor = torch.rand(3,6)
print(tensor)

t1, t2, t3 = torch.chunk(tensor, 3, dim = 1)
print(t1)
print(t2)
print(t3)

tensor([[0.4435, 0.8465, 0.0658, 0.5513, 0.1067, 0.4230],
        [0.8089, 0.2242, 0.2853, 0.7421, 0.4301, 0.0955],
        [0.4549, 0.3276, 0.6084, 0.2432, 0.2447, 0.4018]])
tensor([[0.4435, 0.8465],
        [0.8089, 0.2242],
        [0.4549, 0.3276]])
tensor([[0.0658, 0.5513],
        [0.2853, 0.7421],
        [0.6084, 0.2432]])
tensor([[0.1067, 0.4230],
        [0.4301, 0.0955],
        [0.2447, 0.4018]])


In [75]:
t1, t2, t3 = torch.chunk(tensor, 3, dim = 0)
print(t1)
print(t2)
print(t3)

tensor([[0.4435, 0.8465, 0.0658, 0.5513, 0.1067, 0.4230]])
tensor([[0.8089, 0.2242, 0.2853, 0.7421, 0.4301, 0.0955]])
tensor([[0.4549, 0.3276, 0.6084, 0.2432, 0.2447, 0.4018]])


In [83]:
# split: chunk 와 동일한 기능이지만 조금 다름, 몇개의 라인
tensor = torch.rand(3,6)
t1, t2 = torch.split(tensor,3,dim=1)
print(tensor)
print(t1)
print(t2)

tensor([[0.7049, 0.0414, 0.7343, 0.0894, 0.2161, 0.3926],
        [0.8293, 0.9111, 0.7108, 0.0106, 0.0970, 0.4035],
        [0.0576, 0.7979, 0.5104, 0.5210, 0.9026, 0.6812]])
tensor([[0.7049, 0.0414, 0.7343],
        [0.8293, 0.9111, 0.7108],
        [0.0576, 0.7979, 0.5104]])
tensor([[0.0894, 0.2161, 0.3926],
        [0.0106, 0.0970, 0.4035],
        [0.5210, 0.9026, 0.6812]])


In [84]:
a = torch.ones(7)
print(a)
b=a.numpy()
print(b)

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]


In [85]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [88]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
print(a)
print(b)
np.add(a,1, out= a)
print(a)
print(b)

[1. 1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


### Autograd (자동미분)

* `torch.autograd' 패키지는 Tensor의 모든 연산에 대해 자동미분 제공
* 이는 코드를 어떻게 작성하여 실행하느냐에 따라 역전파가 정의된다는 뜻
* `backprop`를 위해 미분값을 자동으로 계싼

`required_grad` 속성을 True로 설정하면, 해당 텐서에서 이루어지는 모든 연산들을 추적하기 시작
기록을 추적하는 것을 중단하게 하려면, `.detach()`를 호출하여 연산기록으로부터 분리

In [89]:
a = torch.randn(3,3)
a = a *3
print(a)
print(a.requires_grad)

tensor([[ 2.2023,  2.2239, -3.5101],
        [-1.3198,  2.8548, -2.6215],
        [ 2.4340, -1.4080,  0.6296]])
False


In [91]:
# requires_grad_() 는 기존 텐서의 requires_grad 값을 in-place
# grad_fn: 미분값을 계산한 함수에 대한 정보 저장

a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b)
print(b.grad_fn)

True
tensor(47.1841, grad_fn=<SumBackward0>)


In [92]:
# gradient
x = torch.ones(3,3, requires_grad = True)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [93]:
y = x+5
print(y)


tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [94]:
z = y*y
out = z.mean()
print(z,out)

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)


In [95]:
print(out)
out.backward()

tensor(36., grad_fn=<MeanBackward0>)


In [96]:
print(x)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [105]:
x = torch.randn(3, requires_grad=True)

y = x *2
while y.data.norm() < 1000:
    y = y*2

print(y)

tensor([-791.0658, -947.7231, -140.5893], grad_fn=<MulBackward0>)


In [106]:
v = torch.tensor([0.1,1.0,0.0001], dtype = torch.float)

In [107]:
y. backward(v)

print(x.grad)

tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])
